### ISSUE TITLE
Bot currently not able to do anything

### ISSUE THREAD

**Issue by TeaJayed** [okkdev/cardian#3] opened 2022-07-22 16:37 UTC
The bot just searches for a couple of minutes, stops and gives an error message.
Set up the bot again on the server but didnt work.

**Comment by okkdev** [comment] 2022-07-22 17:28
Unfortunately there's nothing I can do at the moment, as that is an issue on Discord's side.
Today Discord added an additional digit to their snowflake IDs, but in the process broke a couple API endpoints. Seems like Cardian is affected because it's using interaction defer.
Let's hope Discord fixes it soon.

**Comment by TeaJayed** [comment] 2022-07-22 17:30
Alright, thanks for the info!

**Comment by okkdev** [comment] 2022-07-22 17:35
I'll leave it open and close it once the issue is resolved on Discord's part. :)

**Comment by okkdev** [comment] 2022-07-22 18:25
Seems to be working again :)

**Closed as completed** 2022-07-22 18:25 UTC
